
following error occured at Wed Mar 07 2018 05:47:37 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'fdgdg' in 'field list'"
following error occured at Wed Mar 07 2018 05:48:24 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'gdfgd' in 'field list'"
following error occured at Wed Mar 07 2018 05:50:45 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'trytrytry' in 'field list'"
following error occured at Wed Mar 07 2018 05:55:38 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Wed Mar 07 2018 05:57:12 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Wed Mar 07 2018 06:00:59 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'ytyrtyt' in 'field list'"
following error occured at Wed Mar 07 2018 06:01:11 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'ytyrtyt' in 'field list'"
following error occured at Wed Mar 07 2018 06:02:10 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'ytyrtyt' in 'field list'"
following error occured at Wed Mar 07 2018 14:21:52 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Wed Mar 07 2018 14:24:12 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Wed Mar 07 2018 14:28:19 GMT+0200 (Jerusalem Standard Time) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"